# Generated by Django 5.1.3 on 2024-11-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
            preserve_default=False,
        ),
    ]
